name = "lyrics-api"
type = "javascript"
account_id = "3f3f7b6b86669a040fcfbf088dc613ae"
zone_id = "0b7fa5b58045e4d5b17579f647b9c002"
route = "lyrics-api.lujjjh.com/*"

[build]
watch_dir = "dist"

[build.upload]
format = "service-worker"
